[workspace]
members = [
    "cli",
    "crates/analysis",
    "crates/apk",
    "crates/engine",
    "crates/ir",
]

resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
authors = ["Yashas P"]
repository = "https://github.com/WRenchJr42/rutken_static_analyzer"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
sha2 = "0.10"
zip = "2"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
